# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven build

on:
  pull_request:
    branches: [ main ]

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build-lib.yml@test-remove-permissions
    with:
      java-version: 11
    secrets: inherit    
